#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyTuyenDung")]
	public partial class DataQuanLiTuyenDungDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblLICH_PV(tblLICH_PV instance);
    partial void UpdatetblLICH_PV(tblLICH_PV instance);
    partial void DeletetblLICH_PV(tblLICH_PV instance);
    partial void InserttblLICHPV_UNGVIEN(tblLICHPV_UNGVIEN instance);
    partial void UpdatetblLICHPV_UNGVIEN(tblLICHPV_UNGVIEN instance);
    partial void DeletetblLICHPV_UNGVIEN(tblLICHPV_UNGVIEN instance);
    partial void InserttblNHANVIEN(tblNHANVIEN instance);
    partial void UpdatetblNHANVIEN(tblNHANVIEN instance);
    partial void DeletetblNHANVIEN(tblNHANVIEN instance);
    partial void InserttblROLE(tblROLE instance);
    partial void UpdatetblROLE(tblROLE instance);
    partial void DeletetblROLE(tblROLE instance);
    partial void InserttblTAIKHOAN(tblTAIKHOAN instance);
    partial void UpdatetblTAIKHOAN(tblTAIKHOAN instance);
    partial void DeletetblTAIKHOAN(tblTAIKHOAN instance);
    partial void InserttblUNGVIEN(tblUNGVIEN instance);
    partial void UpdatetblUNGVIEN(tblUNGVIEN instance);
    partial void DeletetblUNGVIEN(tblUNGVIEN instance);
    partial void InserttblVITRI_TD(tblVITRI_TD instance);
    partial void UpdatetblVITRI_TD(tblVITRI_TD instance);
    partial void DeletetblVITRI_TD(tblVITRI_TD instance);
    partial void InserttblVTTD_UNGTUYEN(tblVTTD_UNGTUYEN instance);
    partial void UpdatetblVTTD_UNGTUYEN(tblVTTD_UNGTUYEN instance);
    partial void DeletetblVTTD_UNGTUYEN(tblVTTD_UNGTUYEN instance);
    partial void InserttblWEB(tblWEB instance);
    partial void UpdatetblWEB(tblWEB instance);
    partial void DeletetblWEB(tblWEB instance);
    #endregion
		
		public DataQuanLiTuyenDungDataContext() : 
				base(global::WindowsFormsApplication1.Properties.Settings.Default.QuanLyTuyenDungConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLiTuyenDungDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLiTuyenDungDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLiTuyenDungDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLiTuyenDungDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblLICH_PV> tblLICH_PVs
		{
			get
			{
				return this.GetTable<tblLICH_PV>();
			}
		}
		
		public System.Data.Linq.Table<tblLICHPV_UNGVIEN> tblLICHPV_UNGVIENs
		{
			get
			{
				return this.GetTable<tblLICHPV_UNGVIEN>();
			}
		}
		
		public System.Data.Linq.Table<tblNHANVIEN> tblNHANVIENs
		{
			get
			{
				return this.GetTable<tblNHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<tblROLE> tblROLEs
		{
			get
			{
				return this.GetTable<tblROLE>();
			}
		}
		
		public System.Data.Linq.Table<tblTAIKHOAN> tblTAIKHOANs
		{
			get
			{
				return this.GetTable<tblTAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<tblUNGVIEN> tblUNGVIENs
		{
			get
			{
				return this.GetTable<tblUNGVIEN>();
			}
		}
		
		public System.Data.Linq.Table<tblVITRI_TD> tblVITRI_TDs
		{
			get
			{
				return this.GetTable<tblVITRI_TD>();
			}
		}
		
		public System.Data.Linq.Table<tblVTTD_UNGTUYEN> tblVTTD_UNGTUYENs
		{
			get
			{
				return this.GetTable<tblVTTD_UNGTUYEN>();
			}
		}
		
		public System.Data.Linq.Table<tblWEB> tblWEBs
		{
			get
			{
				return this.GetTable<tblWEB>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLICH_PV")]
	public partial class tblLICH_PV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLich;
		
		private System.Nullable<System.DateTime> _ThoiGian;
		
		private string _DiaDiem;
		
		private System.Nullable<int> _ID_NV;
		
		private EntitySet<tblLICHPV_UNGVIEN> _tblLICHPV_UNGVIENs;
		
		private EntityRef<tblNHANVIEN> _tblNHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLichChanging(int value);
    partial void OnMaLichChanged();
    partial void OnThoiGianChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianChanged();
    partial void OnDiaDiemChanging(string value);
    partial void OnDiaDiemChanged();
    partial void OnID_NVChanging(System.Nullable<int> value);
    partial void OnID_NVChanged();
    #endregion
		
		public tblLICH_PV()
		{
			this._tblLICHPV_UNGVIENs = new EntitySet<tblLICHPV_UNGVIEN>(new Action<tblLICHPV_UNGVIEN>(this.attach_tblLICHPV_UNGVIENs), new Action<tblLICHPV_UNGVIEN>(this.detach_tblLICHPV_UNGVIENs));
			this._tblNHANVIEN = default(EntityRef<tblNHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLich", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLich
		{
			get
			{
				return this._MaLich;
			}
			set
			{
				if ((this._MaLich != value))
				{
					this.OnMaLichChanging(value);
					this.SendPropertyChanging();
					this._MaLich = value;
					this.SendPropertyChanged("MaLich");
					this.OnMaLichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(100)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this.OnDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._DiaDiem = value;
					this.SendPropertyChanged("DiaDiem");
					this.OnDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NV", DbType="Int")]
		public System.Nullable<int> ID_NV
		{
			get
			{
				return this._ID_NV;
			}
			set
			{
				if ((this._ID_NV != value))
				{
					if (this._tblNHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NVChanging(value);
					this.SendPropertyChanging();
					this._ID_NV = value;
					this.SendPropertyChanged("ID_NV");
					this.OnID_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLICH_PV_tblLICHPV_UNGVIEN", Storage="_tblLICHPV_UNGVIENs", ThisKey="MaLich", OtherKey="MaLich")]
		public EntitySet<tblLICHPV_UNGVIEN> tblLICHPV_UNGVIENs
		{
			get
			{
				return this._tblLICHPV_UNGVIENs;
			}
			set
			{
				this._tblLICHPV_UNGVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblLICH_PV", Storage="_tblNHANVIEN", ThisKey="ID_NV", OtherKey="ID", IsForeignKey=true)]
		public tblNHANVIEN tblNHANVIEN
		{
			get
			{
				return this._tblNHANVIEN.Entity;
			}
			set
			{
				tblNHANVIEN previousValue = this._tblNHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tblNHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNHANVIEN.Entity = null;
						previousValue.tblLICH_PVs.Remove(this);
					}
					this._tblNHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tblLICH_PVs.Add(this);
						this._ID_NV = value.ID;
					}
					else
					{
						this._ID_NV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblNHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblLICHPV_UNGVIENs(tblLICHPV_UNGVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tblLICH_PV = this;
		}
		
		private void detach_tblLICHPV_UNGVIENs(tblLICHPV_UNGVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tblLICH_PV = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLICHPV_UNGVIEN")]
	public partial class tblLICHPV_UNGVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaUV_UV;
		
		private int _MaVT_VT;
		
		private int _MaLich;
		
		private EntityRef<tblLICH_PV> _tblLICH_PV;
		
		private EntityRef<tblUNGVIEN> _tblUNGVIEN;
		
		private EntityRef<tblVITRI_TD> _tblVITRI_TD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaUV_UVChanging(int value);
    partial void OnMaUV_UVChanged();
    partial void OnMaVT_VTChanging(int value);
    partial void OnMaVT_VTChanged();
    partial void OnMaLichChanging(int value);
    partial void OnMaLichChanged();
    #endregion
		
		public tblLICHPV_UNGVIEN()
		{
			this._tblLICH_PV = default(EntityRef<tblLICH_PV>);
			this._tblUNGVIEN = default(EntityRef<tblUNGVIEN>);
			this._tblVITRI_TD = default(EntityRef<tblVITRI_TD>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaUV_UV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaUV_UV
		{
			get
			{
				return this._MaUV_UV;
			}
			set
			{
				if ((this._MaUV_UV != value))
				{
					if (this._tblUNGVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaUV_UVChanging(value);
					this.SendPropertyChanging();
					this._MaUV_UV = value;
					this.SendPropertyChanged("MaUV_UV");
					this.OnMaUV_UVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVT_VT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaVT_VT
		{
			get
			{
				return this._MaVT_VT;
			}
			set
			{
				if ((this._MaVT_VT != value))
				{
					if (this._tblVITRI_TD.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaVT_VTChanging(value);
					this.SendPropertyChanging();
					this._MaVT_VT = value;
					this.SendPropertyChanged("MaVT_VT");
					this.OnMaVT_VTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLich", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaLich
		{
			get
			{
				return this._MaLich;
			}
			set
			{
				if ((this._MaLich != value))
				{
					if (this._tblLICH_PV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLichChanging(value);
					this.SendPropertyChanging();
					this._MaLich = value;
					this.SendPropertyChanged("MaLich");
					this.OnMaLichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLICH_PV_tblLICHPV_UNGVIEN", Storage="_tblLICH_PV", ThisKey="MaLich", OtherKey="MaLich", IsForeignKey=true)]
		public tblLICH_PV tblLICH_PV
		{
			get
			{
				return this._tblLICH_PV.Entity;
			}
			set
			{
				tblLICH_PV previousValue = this._tblLICH_PV.Entity;
				if (((previousValue != value) 
							|| (this._tblLICH_PV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblLICH_PV.Entity = null;
						previousValue.tblLICHPV_UNGVIENs.Remove(this);
					}
					this._tblLICH_PV.Entity = value;
					if ((value != null))
					{
						value.tblLICHPV_UNGVIENs.Add(this);
						this._MaLich = value.MaLich;
					}
					else
					{
						this._MaLich = default(int);
					}
					this.SendPropertyChanged("tblLICH_PV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUNGVIEN_tblLICHPV_UNGVIEN", Storage="_tblUNGVIEN", ThisKey="MaUV_UV", OtherKey="MaUV", IsForeignKey=true)]
		public tblUNGVIEN tblUNGVIEN
		{
			get
			{
				return this._tblUNGVIEN.Entity;
			}
			set
			{
				tblUNGVIEN previousValue = this._tblUNGVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tblUNGVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUNGVIEN.Entity = null;
						previousValue.tblLICHPV_UNGVIENs.Remove(this);
					}
					this._tblUNGVIEN.Entity = value;
					if ((value != null))
					{
						value.tblLICHPV_UNGVIENs.Add(this);
						this._MaUV_UV = value.MaUV;
					}
					else
					{
						this._MaUV_UV = default(int);
					}
					this.SendPropertyChanged("tblUNGVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVITRI_TD_tblLICHPV_UNGVIEN", Storage="_tblVITRI_TD", ThisKey="MaVT_VT", OtherKey="MaVT", IsForeignKey=true)]
		public tblVITRI_TD tblVITRI_TD
		{
			get
			{
				return this._tblVITRI_TD.Entity;
			}
			set
			{
				tblVITRI_TD previousValue = this._tblVITRI_TD.Entity;
				if (((previousValue != value) 
							|| (this._tblVITRI_TD.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblVITRI_TD.Entity = null;
						previousValue.tblLICHPV_UNGVIENs.Remove(this);
					}
					this._tblVITRI_TD.Entity = value;
					if ((value != null))
					{
						value.tblLICHPV_UNGVIENs.Add(this);
						this._MaVT_VT = value.MaVT;
					}
					else
					{
						this._MaVT_VT = default(int);
					}
					this.SendPropertyChanged("tblVITRI_TD");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNHANVIEN")]
	public partial class tblNHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenNV;
		
		private string _ChucVu;
		
		private EntitySet<tblLICH_PV> _tblLICH_PVs;
		
		private EntityRef<tblTAIKHOAN> _tblTAIKHOAN;
		
		private EntitySet<tblUNGVIEN> _tblUNGVIENs;
		
		private EntitySet<tblVITRI_TD> _tblVITRI_TDs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    #endregion
		
		public tblNHANVIEN()
		{
			this._tblLICH_PVs = new EntitySet<tblLICH_PV>(new Action<tblLICH_PV>(this.attach_tblLICH_PVs), new Action<tblLICH_PV>(this.detach_tblLICH_PVs));
			this._tblTAIKHOAN = default(EntityRef<tblTAIKHOAN>);
			this._tblUNGVIENs = new EntitySet<tblUNGVIEN>(new Action<tblUNGVIEN>(this.attach_tblUNGVIENs), new Action<tblUNGVIEN>(this.detach_tblUNGVIENs));
			this._tblVITRI_TDs = new EntitySet<tblVITRI_TD>(new Action<tblVITRI_TD>(this.attach_tblVITRI_TDs), new Action<tblVITRI_TD>(this.detach_tblVITRI_TDs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(40)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(20)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblLICH_PV", Storage="_tblLICH_PVs", ThisKey="ID", OtherKey="ID_NV")]
		public EntitySet<tblLICH_PV> tblLICH_PVs
		{
			get
			{
				return this._tblLICH_PVs;
			}
			set
			{
				this._tblLICH_PVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblTAIKHOAN", Storage="_tblTAIKHOAN", ThisKey="ID", OtherKey="ID_NV", IsUnique=true, IsForeignKey=false)]
		public tblTAIKHOAN tblTAIKHOAN
		{
			get
			{
				return this._tblTAIKHOAN.Entity;
			}
			set
			{
				tblTAIKHOAN previousValue = this._tblTAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._tblTAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblTAIKHOAN.Entity = null;
						previousValue.tblNHANVIEN = null;
					}
					this._tblTAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.tblNHANVIEN = this;
					}
					this.SendPropertyChanged("tblTAIKHOAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblUNGVIEN", Storage="_tblUNGVIENs", ThisKey="ID", OtherKey="ID_NV")]
		public EntitySet<tblUNGVIEN> tblUNGVIENs
		{
			get
			{
				return this._tblUNGVIENs;
			}
			set
			{
				this._tblUNGVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblVITRI_TD", Storage="_tblVITRI_TDs", ThisKey="ID", OtherKey="ID_NV")]
		public EntitySet<tblVITRI_TD> tblVITRI_TDs
		{
			get
			{
				return this._tblVITRI_TDs;
			}
			set
			{
				this._tblVITRI_TDs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblLICH_PVs(tblLICH_PV entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = this;
		}
		
		private void detach_tblLICH_PVs(tblLICH_PV entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = null;
		}
		
		private void attach_tblUNGVIENs(tblUNGVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = this;
		}
		
		private void detach_tblUNGVIENs(tblUNGVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = null;
		}
		
		private void attach_tblVITRI_TDs(tblVITRI_TD entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = this;
		}
		
		private void detach_tblVITRI_TDs(tblVITRI_TD entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblROLE")]
	public partial class tblROLE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaRole;
		
		private string _TenRole;
		
		private string _MoTa;
		
		private EntitySet<tblTAIKHOAN> _tblTAIKHOANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaRoleChanging(int value);
    partial void OnMaRoleChanged();
    partial void OnTenRoleChanging(string value);
    partial void OnTenRoleChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public tblROLE()
		{
			this._tblTAIKHOANs = new EntitySet<tblTAIKHOAN>(new Action<tblTAIKHOAN>(this.attach_tblTAIKHOANs), new Action<tblTAIKHOAN>(this.detach_tblTAIKHOANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaRole", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaRole
		{
			get
			{
				return this._MaRole;
			}
			set
			{
				if ((this._MaRole != value))
				{
					this.OnMaRoleChanging(value);
					this.SendPropertyChanging();
					this._MaRole = value;
					this.SendPropertyChanged("MaRole");
					this.OnMaRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenRole", DbType="NVarChar(20)")]
		public string TenRole
		{
			get
			{
				return this._TenRole;
			}
			set
			{
				if ((this._TenRole != value))
				{
					this.OnTenRoleChanging(value);
					this.SendPropertyChanging();
					this._TenRole = value;
					this.SendPropertyChanged("TenRole");
					this.OnTenRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(100)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblROLE_tblTAIKHOAN", Storage="_tblTAIKHOANs", ThisKey="MaRole", OtherKey="MaRole_R")]
		public EntitySet<tblTAIKHOAN> tblTAIKHOANs
		{
			get
			{
				return this._tblTAIKHOANs;
			}
			set
			{
				this._tblTAIKHOANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblTAIKHOANs(tblTAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.tblROLE = this;
		}
		
		private void detach_tblTAIKHOANs(tblTAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.tblROLE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTAIKHOAN")]
	public partial class tblTAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_NV;
		
		private string _Usernames;
		
		private string _Passwords;
		
		private System.Nullable<int> _MaRole_R;
		
		private EntityRef<tblNHANVIEN> _tblNHANVIEN;
		
		private EntityRef<tblROLE> _tblROLE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_NVChanging(int value);
    partial void OnID_NVChanged();
    partial void OnUsernamesChanging(string value);
    partial void OnUsernamesChanged();
    partial void OnPasswordsChanging(string value);
    partial void OnPasswordsChanged();
    partial void OnMaRole_RChanging(System.Nullable<int> value);
    partial void OnMaRole_RChanged();
    #endregion
		
		public tblTAIKHOAN()
		{
			this._tblNHANVIEN = default(EntityRef<tblNHANVIEN>);
			this._tblROLE = default(EntityRef<tblROLE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_NV
		{
			get
			{
				return this._ID_NV;
			}
			set
			{
				if ((this._ID_NV != value))
				{
					if (this._tblNHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NVChanging(value);
					this.SendPropertyChanging();
					this._ID_NV = value;
					this.SendPropertyChanged("ID_NV");
					this.OnID_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usernames", DbType="VarChar(10)")]
		public string Usernames
		{
			get
			{
				return this._Usernames;
			}
			set
			{
				if ((this._Usernames != value))
				{
					this.OnUsernamesChanging(value);
					this.SendPropertyChanging();
					this._Usernames = value;
					this.SendPropertyChanged("Usernames");
					this.OnUsernamesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passwords", DbType="VarChar(20)")]
		public string Passwords
		{
			get
			{
				return this._Passwords;
			}
			set
			{
				if ((this._Passwords != value))
				{
					this.OnPasswordsChanging(value);
					this.SendPropertyChanging();
					this._Passwords = value;
					this.SendPropertyChanged("Passwords");
					this.OnPasswordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaRole_R", DbType="Int")]
		public System.Nullable<int> MaRole_R
		{
			get
			{
				return this._MaRole_R;
			}
			set
			{
				if ((this._MaRole_R != value))
				{
					if (this._tblROLE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaRole_RChanging(value);
					this.SendPropertyChanging();
					this._MaRole_R = value;
					this.SendPropertyChanged("MaRole_R");
					this.OnMaRole_RChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblTAIKHOAN", Storage="_tblNHANVIEN", ThisKey="ID_NV", OtherKey="ID", IsForeignKey=true)]
		public tblNHANVIEN tblNHANVIEN
		{
			get
			{
				return this._tblNHANVIEN.Entity;
			}
			set
			{
				tblNHANVIEN previousValue = this._tblNHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tblNHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNHANVIEN.Entity = null;
						previousValue.tblTAIKHOAN = null;
					}
					this._tblNHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tblTAIKHOAN = this;
						this._ID_NV = value.ID;
					}
					else
					{
						this._ID_NV = default(int);
					}
					this.SendPropertyChanged("tblNHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblROLE_tblTAIKHOAN", Storage="_tblROLE", ThisKey="MaRole_R", OtherKey="MaRole", IsForeignKey=true)]
		public tblROLE tblROLE
		{
			get
			{
				return this._tblROLE.Entity;
			}
			set
			{
				tblROLE previousValue = this._tblROLE.Entity;
				if (((previousValue != value) 
							|| (this._tblROLE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblROLE.Entity = null;
						previousValue.tblTAIKHOANs.Remove(this);
					}
					this._tblROLE.Entity = value;
					if ((value != null))
					{
						value.tblTAIKHOANs.Add(this);
						this._MaRole_R = value.MaRole;
					}
					else
					{
						this._MaRole_R = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblROLE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUNGVIEN")]
	public partial class tblUNGVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaUV;
		
		private string _TenUV;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<long> _CMND;
		
		private string _Email;
		
		private string _SDT;
		
		private string _TrinhDoHV;
		
		private string _NgoaiNgu;
		
		private System.Nullable<int> _SoNamKN;
		
		private System.Data.Linq.Binary _CV;
		
		private System.Nullable<int> _ID_NV;
		
		private EntitySet<tblLICHPV_UNGVIEN> _tblLICHPV_UNGVIENs;
		
		private EntitySet<tblVTTD_UNGTUYEN> _tblVTTD_UNGTUYENs;
		
		private EntityRef<tblNHANVIEN> _tblNHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaUVChanging(int value);
    partial void OnMaUVChanged();
    partial void OnTenUVChanging(string value);
    partial void OnTenUVChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnCMNDChanging(System.Nullable<long> value);
    partial void OnCMNDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnTrinhDoHVChanging(string value);
    partial void OnTrinhDoHVChanged();
    partial void OnNgoaiNguChanging(string value);
    partial void OnNgoaiNguChanged();
    partial void OnSoNamKNChanging(System.Nullable<int> value);
    partial void OnSoNamKNChanged();
    partial void OnCVChanging(System.Data.Linq.Binary value);
    partial void OnCVChanged();
    partial void OnID_NVChanging(System.Nullable<int> value);
    partial void OnID_NVChanged();
    #endregion
		
		public tblUNGVIEN()
		{
			this._tblLICHPV_UNGVIENs = new EntitySet<tblLICHPV_UNGVIEN>(new Action<tblLICHPV_UNGVIEN>(this.attach_tblLICHPV_UNGVIENs), new Action<tblLICHPV_UNGVIEN>(this.detach_tblLICHPV_UNGVIENs));
			this._tblVTTD_UNGTUYENs = new EntitySet<tblVTTD_UNGTUYEN>(new Action<tblVTTD_UNGTUYEN>(this.attach_tblVTTD_UNGTUYENs), new Action<tblVTTD_UNGTUYEN>(this.detach_tblVTTD_UNGTUYENs));
			this._tblNHANVIEN = default(EntityRef<tblNHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaUV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaUV
		{
			get
			{
				return this._MaUV;
			}
			set
			{
				if ((this._MaUV != value))
				{
					this.OnMaUVChanging(value);
					this.SendPropertyChanging();
					this._MaUV = value;
					this.SendPropertyChanged("MaUV");
					this.OnMaUVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenUV", DbType="NVarChar(40)")]
		public string TenUV
		{
			get
			{
				return this._TenUV;
			}
			set
			{
				if ((this._TenUV != value))
				{
					this.OnTenUVChanging(value);
					this.SendPropertyChanging();
					this._TenUV = value;
					this.SendPropertyChanged("TenUV");
					this.OnTenUVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="BigInt")]
		public System.Nullable<long> CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDoHV", DbType="NVarChar(20)")]
		public string TrinhDoHV
		{
			get
			{
				return this._TrinhDoHV;
			}
			set
			{
				if ((this._TrinhDoHV != value))
				{
					this.OnTrinhDoHVChanging(value);
					this.SendPropertyChanging();
					this._TrinhDoHV = value;
					this.SendPropertyChanged("TrinhDoHV");
					this.OnTrinhDoHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgoaiNgu", DbType="NVarChar(10)")]
		public string NgoaiNgu
		{
			get
			{
				return this._NgoaiNgu;
			}
			set
			{
				if ((this._NgoaiNgu != value))
				{
					this.OnNgoaiNguChanging(value);
					this.SendPropertyChanging();
					this._NgoaiNgu = value;
					this.SendPropertyChanged("NgoaiNgu");
					this.OnNgoaiNguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNamKN", DbType="Int")]
		public System.Nullable<int> SoNamKN
		{
			get
			{
				return this._SoNamKN;
			}
			set
			{
				if ((this._SoNamKN != value))
				{
					this.OnSoNamKNChanging(value);
					this.SendPropertyChanging();
					this._SoNamKN = value;
					this.SendPropertyChanged("SoNamKN");
					this.OnSoNamKNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CV", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary CV
		{
			get
			{
				return this._CV;
			}
			set
			{
				if ((this._CV != value))
				{
					this.OnCVChanging(value);
					this.SendPropertyChanging();
					this._CV = value;
					this.SendPropertyChanged("CV");
					this.OnCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NV", DbType="Int")]
		public System.Nullable<int> ID_NV
		{
			get
			{
				return this._ID_NV;
			}
			set
			{
				if ((this._ID_NV != value))
				{
					if (this._tblNHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NVChanging(value);
					this.SendPropertyChanging();
					this._ID_NV = value;
					this.SendPropertyChanged("ID_NV");
					this.OnID_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUNGVIEN_tblLICHPV_UNGVIEN", Storage="_tblLICHPV_UNGVIENs", ThisKey="MaUV", OtherKey="MaUV_UV")]
		public EntitySet<tblLICHPV_UNGVIEN> tblLICHPV_UNGVIENs
		{
			get
			{
				return this._tblLICHPV_UNGVIENs;
			}
			set
			{
				this._tblLICHPV_UNGVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUNGVIEN_tblVTTD_UNGTUYEN", Storage="_tblVTTD_UNGTUYENs", ThisKey="MaUV", OtherKey="MaUV_UV")]
		public EntitySet<tblVTTD_UNGTUYEN> tblVTTD_UNGTUYENs
		{
			get
			{
				return this._tblVTTD_UNGTUYENs;
			}
			set
			{
				this._tblVTTD_UNGTUYENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblUNGVIEN", Storage="_tblNHANVIEN", ThisKey="ID_NV", OtherKey="ID", IsForeignKey=true)]
		public tblNHANVIEN tblNHANVIEN
		{
			get
			{
				return this._tblNHANVIEN.Entity;
			}
			set
			{
				tblNHANVIEN previousValue = this._tblNHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tblNHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNHANVIEN.Entity = null;
						previousValue.tblUNGVIENs.Remove(this);
					}
					this._tblNHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tblUNGVIENs.Add(this);
						this._ID_NV = value.ID;
					}
					else
					{
						this._ID_NV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblNHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblLICHPV_UNGVIENs(tblLICHPV_UNGVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tblUNGVIEN = this;
		}
		
		private void detach_tblLICHPV_UNGVIENs(tblLICHPV_UNGVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tblUNGVIEN = null;
		}
		
		private void attach_tblVTTD_UNGTUYENs(tblVTTD_UNGTUYEN entity)
		{
			this.SendPropertyChanging();
			entity.tblUNGVIEN = this;
		}
		
		private void detach_tblVTTD_UNGTUYENs(tblVTTD_UNGTUYEN entity)
		{
			this.SendPropertyChanging();
			entity.tblUNGVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblVITRI_TD")]
	public partial class tblVITRI_TD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaVT;
		
		private string _TenVT;
		
		private System.Nullable<int> _SoLuong;
		
		private string _DiaDiemLV;
		
		private string _Luong;
		
		private System.Nullable<System.DateTime> _NgayHetHan;
		
		private string _MoTa;
		
		private string _YeuCau;
		
		private string _QuyenLoi;
		
		private System.Nullable<int> _ID_NV;
		
		private EntitySet<tblLICHPV_UNGVIEN> _tblLICHPV_UNGVIENs;
		
		private EntitySet<tblVTTD_UNGTUYEN> _tblVTTD_UNGTUYENs;
		
		private EntityRef<tblNHANVIEN> _tblNHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaVTChanging(int value);
    partial void OnMaVTChanged();
    partial void OnTenVTChanging(string value);
    partial void OnTenVTChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnDiaDiemLVChanging(string value);
    partial void OnDiaDiemLVChanged();
    partial void OnLuongChanging(string value);
    partial void OnLuongChanged();
    partial void OnNgayHetHanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHetHanChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnYeuCauChanging(string value);
    partial void OnYeuCauChanged();
    partial void OnQuyenLoiChanging(string value);
    partial void OnQuyenLoiChanged();
    partial void OnID_NVChanging(System.Nullable<int> value);
    partial void OnID_NVChanged();
    #endregion
		
		public tblVITRI_TD()
		{
			this._tblLICHPV_UNGVIENs = new EntitySet<tblLICHPV_UNGVIEN>(new Action<tblLICHPV_UNGVIEN>(this.attach_tblLICHPV_UNGVIENs), new Action<tblLICHPV_UNGVIEN>(this.detach_tblLICHPV_UNGVIENs));
			this._tblVTTD_UNGTUYENs = new EntitySet<tblVTTD_UNGTUYEN>(new Action<tblVTTD_UNGTUYEN>(this.attach_tblVTTD_UNGTUYENs), new Action<tblVTTD_UNGTUYEN>(this.detach_tblVTTD_UNGTUYENs));
			this._tblNHANVIEN = default(EntityRef<tblNHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaVT
		{
			get
			{
				return this._MaVT;
			}
			set
			{
				if ((this._MaVT != value))
				{
					this.OnMaVTChanging(value);
					this.SendPropertyChanging();
					this._MaVT = value;
					this.SendPropertyChanged("MaVT");
					this.OnMaVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVT", DbType="NVarChar(20)")]
		public string TenVT
		{
			get
			{
				return this._TenVT;
			}
			set
			{
				if ((this._TenVT != value))
				{
					this.OnTenVTChanging(value);
					this.SendPropertyChanging();
					this._TenVT = value;
					this.SendPropertyChanged("TenVT");
					this.OnTenVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiemLV", DbType="NVarChar(50)")]
		public string DiaDiemLV
		{
			get
			{
				return this._DiaDiemLV;
			}
			set
			{
				if ((this._DiaDiemLV != value))
				{
					this.OnDiaDiemLVChanging(value);
					this.SendPropertyChanging();
					this._DiaDiemLV = value;
					this.SendPropertyChanged("DiaDiemLV");
					this.OnDiaDiemLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luong", DbType="NVarChar(30)")]
		public string Luong
		{
			get
			{
				return this._Luong;
			}
			set
			{
				if ((this._Luong != value))
				{
					this.OnLuongChanging(value);
					this.SendPropertyChanging();
					this._Luong = value;
					this.SendPropertyChanged("Luong");
					this.OnLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this.OnNgayHetHanChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHan = value;
					this.SendPropertyChanged("NgayHetHan");
					this.OnNgayHetHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCau", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string YeuCau
		{
			get
			{
				return this._YeuCau;
			}
			set
			{
				if ((this._YeuCau != value))
				{
					this.OnYeuCauChanging(value);
					this.SendPropertyChanging();
					this._YeuCau = value;
					this.SendPropertyChanged("YeuCau");
					this.OnYeuCauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyenLoi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string QuyenLoi
		{
			get
			{
				return this._QuyenLoi;
			}
			set
			{
				if ((this._QuyenLoi != value))
				{
					this.OnQuyenLoiChanging(value);
					this.SendPropertyChanging();
					this._QuyenLoi = value;
					this.SendPropertyChanged("QuyenLoi");
					this.OnQuyenLoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NV", DbType="Int")]
		public System.Nullable<int> ID_NV
		{
			get
			{
				return this._ID_NV;
			}
			set
			{
				if ((this._ID_NV != value))
				{
					if (this._tblNHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_NVChanging(value);
					this.SendPropertyChanging();
					this._ID_NV = value;
					this.SendPropertyChanged("ID_NV");
					this.OnID_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVITRI_TD_tblLICHPV_UNGVIEN", Storage="_tblLICHPV_UNGVIENs", ThisKey="MaVT", OtherKey="MaVT_VT")]
		public EntitySet<tblLICHPV_UNGVIEN> tblLICHPV_UNGVIENs
		{
			get
			{
				return this._tblLICHPV_UNGVIENs;
			}
			set
			{
				this._tblLICHPV_UNGVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVITRI_TD_tblVTTD_UNGTUYEN", Storage="_tblVTTD_UNGTUYENs", ThisKey="MaVT", OtherKey="MaVT_VT")]
		public EntitySet<tblVTTD_UNGTUYEN> tblVTTD_UNGTUYENs
		{
			get
			{
				return this._tblVTTD_UNGTUYENs;
			}
			set
			{
				this._tblVTTD_UNGTUYENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblVITRI_TD", Storage="_tblNHANVIEN", ThisKey="ID_NV", OtherKey="ID", IsForeignKey=true)]
		public tblNHANVIEN tblNHANVIEN
		{
			get
			{
				return this._tblNHANVIEN.Entity;
			}
			set
			{
				tblNHANVIEN previousValue = this._tblNHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tblNHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNHANVIEN.Entity = null;
						previousValue.tblVITRI_TDs.Remove(this);
					}
					this._tblNHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tblVITRI_TDs.Add(this);
						this._ID_NV = value.ID;
					}
					else
					{
						this._ID_NV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblNHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblLICHPV_UNGVIENs(tblLICHPV_UNGVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tblVITRI_TD = this;
		}
		
		private void detach_tblLICHPV_UNGVIENs(tblLICHPV_UNGVIEN entity)
		{
			this.SendPropertyChanging();
			entity.tblVITRI_TD = null;
		}
		
		private void attach_tblVTTD_UNGTUYENs(tblVTTD_UNGTUYEN entity)
		{
			this.SendPropertyChanging();
			entity.tblVITRI_TD = this;
		}
		
		private void detach_tblVTTD_UNGTUYENs(tblVTTD_UNGTUYEN entity)
		{
			this.SendPropertyChanging();
			entity.tblVITRI_TD = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblVTTD_UNGTUYEN")]
	public partial class tblVTTD_UNGTUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaUV_UV;
		
		private int _MaVT_VT;
		
		private System.Nullable<bool> _TrangThaiDC;
		
		private System.Nullable<bool> _TrangThaiPD;
		
		private EntityRef<tblUNGVIEN> _tblUNGVIEN;
		
		private EntityRef<tblVITRI_TD> _tblVITRI_TD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaUV_UVChanging(int value);
    partial void OnMaUV_UVChanged();
    partial void OnMaVT_VTChanging(int value);
    partial void OnMaVT_VTChanged();
    partial void OnTrangThaiDCChanging(System.Nullable<bool> value);
    partial void OnTrangThaiDCChanged();
    partial void OnTrangThaiPDChanging(System.Nullable<bool> value);
    partial void OnTrangThaiPDChanged();
    #endregion
		
		public tblVTTD_UNGTUYEN()
		{
			this._tblUNGVIEN = default(EntityRef<tblUNGVIEN>);
			this._tblVITRI_TD = default(EntityRef<tblVITRI_TD>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaUV_UV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaUV_UV
		{
			get
			{
				return this._MaUV_UV;
			}
			set
			{
				if ((this._MaUV_UV != value))
				{
					if (this._tblUNGVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaUV_UVChanging(value);
					this.SendPropertyChanging();
					this._MaUV_UV = value;
					this.SendPropertyChanged("MaUV_UV");
					this.OnMaUV_UVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVT_VT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaVT_VT
		{
			get
			{
				return this._MaVT_VT;
			}
			set
			{
				if ((this._MaVT_VT != value))
				{
					if (this._tblVITRI_TD.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaVT_VTChanging(value);
					this.SendPropertyChanging();
					this._MaVT_VT = value;
					this.SendPropertyChanged("MaVT_VT");
					this.OnMaVT_VTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiDC", DbType="Bit")]
		public System.Nullable<bool> TrangThaiDC
		{
			get
			{
				return this._TrangThaiDC;
			}
			set
			{
				if ((this._TrangThaiDC != value))
				{
					this.OnTrangThaiDCChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiDC = value;
					this.SendPropertyChanged("TrangThaiDC");
					this.OnTrangThaiDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiPD", DbType="Bit")]
		public System.Nullable<bool> TrangThaiPD
		{
			get
			{
				return this._TrangThaiPD;
			}
			set
			{
				if ((this._TrangThaiPD != value))
				{
					this.OnTrangThaiPDChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiPD = value;
					this.SendPropertyChanged("TrangThaiPD");
					this.OnTrangThaiPDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUNGVIEN_tblVTTD_UNGTUYEN", Storage="_tblUNGVIEN", ThisKey="MaUV_UV", OtherKey="MaUV", IsForeignKey=true)]
		public tblUNGVIEN tblUNGVIEN
		{
			get
			{
				return this._tblUNGVIEN.Entity;
			}
			set
			{
				tblUNGVIEN previousValue = this._tblUNGVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tblUNGVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUNGVIEN.Entity = null;
						previousValue.tblVTTD_UNGTUYENs.Remove(this);
					}
					this._tblUNGVIEN.Entity = value;
					if ((value != null))
					{
						value.tblVTTD_UNGTUYENs.Add(this);
						this._MaUV_UV = value.MaUV;
					}
					else
					{
						this._MaUV_UV = default(int);
					}
					this.SendPropertyChanged("tblUNGVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblVITRI_TD_tblVTTD_UNGTUYEN", Storage="_tblVITRI_TD", ThisKey="MaVT_VT", OtherKey="MaVT", IsForeignKey=true)]
		public tblVITRI_TD tblVITRI_TD
		{
			get
			{
				return this._tblVITRI_TD.Entity;
			}
			set
			{
				tblVITRI_TD previousValue = this._tblVITRI_TD.Entity;
				if (((previousValue != value) 
							|| (this._tblVITRI_TD.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblVITRI_TD.Entity = null;
						previousValue.tblVTTD_UNGTUYENs.Remove(this);
					}
					this._tblVITRI_TD.Entity = value;
					if ((value != null))
					{
						value.tblVTTD_UNGTUYENs.Add(this);
						this._MaVT_VT = value.MaVT;
					}
					else
					{
						this._MaVT_VT = default(int);
					}
					this.SendPropertyChanged("tblVITRI_TD");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblWEB")]
	public partial class tblWEB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaWeb;
		
		private string _TenWeb;
		
		private string _Link;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaWebChanging(int value);
    partial void OnMaWebChanged();
    partial void OnTenWebChanging(string value);
    partial void OnTenWebChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    #endregion
		
		public tblWEB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaWeb", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaWeb
		{
			get
			{
				return this._MaWeb;
			}
			set
			{
				if ((this._MaWeb != value))
				{
					this.OnMaWebChanging(value);
					this.SendPropertyChanging();
					this._MaWeb = value;
					this.SendPropertyChanged("MaWeb");
					this.OnMaWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenWeb", DbType="NVarChar(40)")]
		public string TenWeb
		{
			get
			{
				return this._TenWeb;
			}
			set
			{
				if ((this._TenWeb != value))
				{
					this.OnTenWebChanging(value);
					this.SendPropertyChanging();
					this._TenWeb = value;
					this.SendPropertyChanged("TenWeb");
					this.OnTenWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="VarChar(30)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
