#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.src.DAOs.DB_WEB1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="webTD1")]
	public partial class DataWebTD1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUNGVIEN(UNGVIEN instance);
    partial void UpdateUNGVIEN(UNGVIEN instance);
    partial void DeleteUNGVIEN(UNGVIEN instance);
    partial void InsertVITRITUYENDUNG(VITRITUYENDUNG instance);
    partial void UpdateVITRITUYENDUNG(VITRITUYENDUNG instance);
    partial void DeleteVITRITUYENDUNG(VITRITUYENDUNG instance);
    partial void InsertVTTD_UNGTUYEN(VTTD_UNGTUYEN instance);
    partial void UpdateVTTD_UNGTUYEN(VTTD_UNGTUYEN instance);
    partial void DeleteVTTD_UNGTUYEN(VTTD_UNGTUYEN instance);
    #endregion
		
		public DataWebTD1DataContext() : 
				base(global::WindowsFormsApplication1.Properties.Settings.Default.webTD1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataWebTD1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataWebTD1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataWebTD1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataWebTD1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UNGVIEN> UNGVIENs
		{
			get
			{
				return this.GetTable<UNGVIEN>();
			}
		}
		
		public System.Data.Linq.Table<VITRITUYENDUNG> VITRITUYENDUNGs
		{
			get
			{
				return this.GetTable<VITRITUYENDUNG>();
			}
		}
		
		public System.Data.Linq.Table<VTTD_UNGTUYEN> VTTD_UNGTUYENs
		{
			get
			{
				return this.GetTable<VTTD_UNGTUYEN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UNGVIEN")]
	public partial class UNGVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaUV;
		
		private string _TenUV;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _CMND;
		
		private string _Email;
		
		private string _SDT;
		
		private string _TrinhDoHV;
		
		private string _NgoaiNgu;
		
		private System.Nullable<int> _SoNamKN;
		
		private string _CV;
		
		private EntitySet<VTTD_UNGTUYEN> _VTTD_UNGTUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaUVChanging(int value);
    partial void OnMaUVChanged();
    partial void OnTenUVChanging(string value);
    partial void OnTenUVChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnTrinhDoHVChanging(string value);
    partial void OnTrinhDoHVChanged();
    partial void OnNgoaiNguChanging(string value);
    partial void OnNgoaiNguChanged();
    partial void OnSoNamKNChanging(System.Nullable<int> value);
    partial void OnSoNamKNChanged();
    partial void OnCVChanging(string value);
    partial void OnCVChanged();
    #endregion
		
		public UNGVIEN()
		{
			this._VTTD_UNGTUYENs = new EntitySet<VTTD_UNGTUYEN>(new Action<VTTD_UNGTUYEN>(this.attach_VTTD_UNGTUYENs), new Action<VTTD_UNGTUYEN>(this.detach_VTTD_UNGTUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaUV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaUV
		{
			get
			{
				return this._MaUV;
			}
			set
			{
				if ((this._MaUV != value))
				{
					this.OnMaUVChanging(value);
					this.SendPropertyChanging();
					this._MaUV = value;
					this.SendPropertyChanged("MaUV");
					this.OnMaUVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenUV", DbType="NVarChar(40)")]
		public string TenUV
		{
			get
			{
				return this._TenUV;
			}
			set
			{
				if ((this._TenUV != value))
				{
					this.OnTenUVChanging(value);
					this.SendPropertyChanging();
					this._TenUV = value;
					this.SendPropertyChanged("TenUV");
					this.OnTenUVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDoHV", DbType="NVarChar(20)")]
		public string TrinhDoHV
		{
			get
			{
				return this._TrinhDoHV;
			}
			set
			{
				if ((this._TrinhDoHV != value))
				{
					this.OnTrinhDoHVChanging(value);
					this.SendPropertyChanging();
					this._TrinhDoHV = value;
					this.SendPropertyChanged("TrinhDoHV");
					this.OnTrinhDoHVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgoaiNgu", DbType="NVarChar(10)")]
		public string NgoaiNgu
		{
			get
			{
				return this._NgoaiNgu;
			}
			set
			{
				if ((this._NgoaiNgu != value))
				{
					this.OnNgoaiNguChanging(value);
					this.SendPropertyChanging();
					this._NgoaiNgu = value;
					this.SendPropertyChanged("NgoaiNgu");
					this.OnNgoaiNguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNamKN", DbType="Int")]
		public System.Nullable<int> SoNamKN
		{
			get
			{
				return this._SoNamKN;
			}
			set
			{
				if ((this._SoNamKN != value))
				{
					this.OnSoNamKNChanging(value);
					this.SendPropertyChanging();
					this._SoNamKN = value;
					this.SendPropertyChanged("SoNamKN");
					this.OnSoNamKNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CV", DbType="VarChar(100)")]
		public string CV
		{
			get
			{
				return this._CV;
			}
			set
			{
				if ((this._CV != value))
				{
					this.OnCVChanging(value);
					this.SendPropertyChanging();
					this._CV = value;
					this.SendPropertyChanged("CV");
					this.OnCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UNGVIEN_VTTD_UNGTUYEN", Storage="_VTTD_UNGTUYENs", ThisKey="MaUV", OtherKey="MaUV_UV")]
		public EntitySet<VTTD_UNGTUYEN> VTTD_UNGTUYENs
		{
			get
			{
				return this._VTTD_UNGTUYENs;
			}
			set
			{
				this._VTTD_UNGTUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VTTD_UNGTUYENs(VTTD_UNGTUYEN entity)
		{
			this.SendPropertyChanging();
			entity.UNGVIEN = this;
		}
		
		private void detach_VTTD_UNGTUYENs(VTTD_UNGTUYEN entity)
		{
			this.SendPropertyChanging();
			entity.UNGVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VITRITUYENDUNG")]
	public partial class VITRITUYENDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaVT;
		
		private string _TenVT;
		
		private EntitySet<VTTD_UNGTUYEN> _VTTD_UNGTUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaVTChanging(int value);
    partial void OnMaVTChanged();
    partial void OnTenVTChanging(string value);
    partial void OnTenVTChanged();
    #endregion
		
		public VITRITUYENDUNG()
		{
			this._VTTD_UNGTUYENs = new EntitySet<VTTD_UNGTUYEN>(new Action<VTTD_UNGTUYEN>(this.attach_VTTD_UNGTUYENs), new Action<VTTD_UNGTUYEN>(this.detach_VTTD_UNGTUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaVT
		{
			get
			{
				return this._MaVT;
			}
			set
			{
				if ((this._MaVT != value))
				{
					this.OnMaVTChanging(value);
					this.SendPropertyChanging();
					this._MaVT = value;
					this.SendPropertyChanged("MaVT");
					this.OnMaVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVT", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string TenVT
		{
			get
			{
				return this._TenVT;
			}
			set
			{
				if ((this._TenVT != value))
				{
					this.OnTenVTChanging(value);
					this.SendPropertyChanging();
					this._TenVT = value;
					this.SendPropertyChanged("TenVT");
					this.OnTenVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VITRITUYENDUNG_VTTD_UNGTUYEN", Storage="_VTTD_UNGTUYENs", ThisKey="MaVT", OtherKey="MaVT_VT")]
		public EntitySet<VTTD_UNGTUYEN> VTTD_UNGTUYENs
		{
			get
			{
				return this._VTTD_UNGTUYENs;
			}
			set
			{
				this._VTTD_UNGTUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VTTD_UNGTUYENs(VTTD_UNGTUYEN entity)
		{
			this.SendPropertyChanging();
			entity.VITRITUYENDUNG = this;
		}
		
		private void detach_VTTD_UNGTUYENs(VTTD_UNGTUYEN entity)
		{
			this.SendPropertyChanging();
			entity.VITRITUYENDUNG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VTTD_UNGTUYEN")]
	public partial class VTTD_UNGTUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaUV_UV;
		
		private int _MaVT_VT;
		
		private EntityRef<UNGVIEN> _UNGVIEN;
		
		private EntityRef<VITRITUYENDUNG> _VITRITUYENDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaUV_UVChanging(int value);
    partial void OnMaUV_UVChanged();
    partial void OnMaVT_VTChanging(int value);
    partial void OnMaVT_VTChanged();
    #endregion
		
		public VTTD_UNGTUYEN()
		{
			this._UNGVIEN = default(EntityRef<UNGVIEN>);
			this._VITRITUYENDUNG = default(EntityRef<VITRITUYENDUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaUV_UV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaUV_UV
		{
			get
			{
				return this._MaUV_UV;
			}
			set
			{
				if ((this._MaUV_UV != value))
				{
					if (this._UNGVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaUV_UVChanging(value);
					this.SendPropertyChanging();
					this._MaUV_UV = value;
					this.SendPropertyChanged("MaUV_UV");
					this.OnMaUV_UVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVT_VT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaVT_VT
		{
			get
			{
				return this._MaVT_VT;
			}
			set
			{
				if ((this._MaVT_VT != value))
				{
					if (this._VITRITUYENDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaVT_VTChanging(value);
					this.SendPropertyChanging();
					this._MaVT_VT = value;
					this.SendPropertyChanged("MaVT_VT");
					this.OnMaVT_VTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UNGVIEN_VTTD_UNGTUYEN", Storage="_UNGVIEN", ThisKey="MaUV_UV", OtherKey="MaUV", IsForeignKey=true)]
		public UNGVIEN UNGVIEN
		{
			get
			{
				return this._UNGVIEN.Entity;
			}
			set
			{
				UNGVIEN previousValue = this._UNGVIEN.Entity;
				if (((previousValue != value) 
							|| (this._UNGVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UNGVIEN.Entity = null;
						previousValue.VTTD_UNGTUYENs.Remove(this);
					}
					this._UNGVIEN.Entity = value;
					if ((value != null))
					{
						value.VTTD_UNGTUYENs.Add(this);
						this._MaUV_UV = value.MaUV;
					}
					else
					{
						this._MaUV_UV = default(int);
					}
					this.SendPropertyChanged("UNGVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VITRITUYENDUNG_VTTD_UNGTUYEN", Storage="_VITRITUYENDUNG", ThisKey="MaVT_VT", OtherKey="MaVT", IsForeignKey=true)]
		public VITRITUYENDUNG VITRITUYENDUNG
		{
			get
			{
				return this._VITRITUYENDUNG.Entity;
			}
			set
			{
				VITRITUYENDUNG previousValue = this._VITRITUYENDUNG.Entity;
				if (((previousValue != value) 
							|| (this._VITRITUYENDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VITRITUYENDUNG.Entity = null;
						previousValue.VTTD_UNGTUYENs.Remove(this);
					}
					this._VITRITUYENDUNG.Entity = value;
					if ((value != null))
					{
						value.VTTD_UNGTUYENs.Add(this);
						this._MaVT_VT = value.MaVT;
					}
					else
					{
						this._MaVT_VT = default(int);
					}
					this.SendPropertyChanged("VITRITUYENDUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
